# Generated by Django 2.1.5 on 2019-01-26 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(blank=True, help_text='设备名可以为空，如果为空，系统将颁发全局唯一标识符作为设备名', max_length=32, null=True, unique=True, verbose_name='设备名称')),
                ('device_secret', models.CharField(editable=False, max_length=16, unique=True, verbose_name='device secret')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '未激活'), (2, '离线'), (3, '在线')], default=1, verbose_name='设备状态')),
                ('last_login', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='最后上线时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'db_table': 'device',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=128, verbose_name='产品名称')),
                ('version', models.CharField(max_length=32, verbose_name='产品版本')),
                ('product_key', models.CharField(editable=False, max_length=11, unique=True, verbose_name='product key')),
                ('product_secret', models.CharField(editable=False, max_length=16, unique=True, verbose_name='product secret')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'db_table': 'product',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='device.Product', verbose_name='所属产品'),
        ),
    ]
