# Generated by Django 2.1.5 on 2019-01-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_secret',
            field=models.CharField(editable=False, max_length=16, unique=True, verbose_name='device secret'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='产品名称'),
        ),
    ]
