# Generated by Django 2.1.5 on 2019-01-27 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_group_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_devices', to='device.Group', verbose_name='所属分组'),
        ),
    ]
